[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "codetext"
version = "0.0.7"
authors = [
  { name="Dung Manh Nguyen", email="dungnm.workspace@gmail.com" },
]
description = "Multilingual programming language parsers for the extract from raw source code into multiple levels of pair data"
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "tree-sitter>=0.20",
    "Levenshtein>=0.20",
    "langdetect>=1.0.0",
    "bs4>=0.0.1",
    "tabulate>=0.9.0"
]

[project.urls]
"Homepage" = "https://github.com/AI4Code-Research/CodeText-data"
"Bug Tracker" = "https://github.com/AI4Code-Research/CodeText-data/issues"

[project.scripts]
codetext = "codetext.__main__:main"
